Repository satyrnidae/foxcraft-dungeon-loot-2, pull requests merged in 2022-08, with the labels that each got.

#37 ✨ Move all items to loot tables - satyrnidae/issue4
  README.md
  config.json
  data/foxcraft_dungeon_loot/advancements/items.json
  data/foxcraft_dungeon_loot/advancements/items/estudinaes_sorrow/player_hurt_entity.json
  data/foxcraft_dungeon_loot/advancements/items/estudinaes_sorrow/player_killed_entity.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/absinthe.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/animus.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/coffee.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/laudanum.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/luma.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/moonshine.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/nectar.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/stout.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/tequila.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/vitae.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/dawncleaver.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/estudinaes_script.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/estudinaes_sorrow.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/fortune_500.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/kobolds_vengeance.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/melimonas_guile.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/palominas_gift.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/peerless_yewhewn.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/skullbasher.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/wand_of_block_state_editing.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/yo_yo_mans_revenge.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/pierce_the_sky.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/shield_of_the_juggernaut.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_disdainful_pride.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_festering_wrath.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_insatiable_hunger.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_lingering_spite.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_seething_hatred.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/wing_of_ouet_zala.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/wing_of_quet_zala.json
  data/foxcraft_dungeon_loot/loot_tables/items/rare/admire_me_from_afar.json
  data/foxcraft_dungeon_loot/loot_tables/items/rare/armor_of_the_golem.json
  data/foxcraft_dungeon_loot/loot_tables/items/rare/longsword.json
  data/foxcraft_dungeon_loot/loot_tables/items/rare/quickdraw_crossbow.json
  data/foxcraft_dungeon_loot/loot_tables/items/rare/shroud_of_notoriety.json
  data/foxcraft_dungeon_loot/loot_tables/items/uncommon/copper_plated_axe.json
  data/foxcraft_dungeon_loot/loot_tables/items/uncommon/copper_plated_hoe.json
  data/foxcraft_dungeon_loot/loot_tables/items/uncommon/copper_plated_pickaxe.json
  data/foxcraft_dungeon_loot/loot_tables/items/uncommon/copper_plated_shovel.json
  data/foxcraft_dungeon_loot/loot_tables/items/uncommon/copper_plated_sword.json
  data/foxcraft_dungeon_loot/predicates/items/boots_broken.json
  data/foxcraft_dungeon_loot/tags/functions/items/give/epic.json
  data/foxcraft_dungeon_loot/tags/functions/items/give/mythic.json
  data/foxcraft_dungeon_loot/tags/functions/items/give/rare.json
  src/foxcraft_dungeon_loot.mc
  src/foxcraft_dungeon_loot/items.mc
  src/foxcraft_dungeon_loot/items/estudinaes_sorrow.mc
  src/foxcraft_dungeon_loot/items/wand_of_block_state_editing.mc
  src/foxcraft_dungeon_loot/items/war_hogs_disdainful_pride.mc
  src/foxcraft_dungeon_loot/items/war_hogs_insatiable_hunger.mc
  src/foxcraft_dungeon_loot/items/war_hogs_seething_hatred.mc
  src/foxcraft_dungeon_loot/items/wing_of_ouet_zala.mc
  src/foxcraft_dungeon_loot/items/wing_of_quet_zala.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/debug_stick.json
Labels: enhancement

#38 🐛 Add Ravager to hostile entity tags
  data/foxcraft_dungeon_loot/tags/entity_types/hostile.json
Labels: bug

#41 ✏️ Reduce snowball search radius to 1, rename files
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/hammer_of_sol.json
  data/foxcraft_dungeon_loot/tags/functions/on_tick.json
  src/foxcraft_dungeon_loot/items/hammer_of_sol.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/hammer_of_sol.json
  texturepack/assets/foxcraft_dungeon_loot/textures/item/hammer_of_sol.png
  texturepack/assets/minecraft/models/item/snowball.json
Labels: enhancement

#39 ✨ Add lucky compass, lucky rabbit's foot, totem of undying, war hog's burning rage, and all armor stands to loot tables
  data/foxcraft_dungeon_loot/loot_tables/items/common/armor_stand.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/armor_stand_baby.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/armor_stand_bashful.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/armor_stand_cancan.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/armor_stand_gallant.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/armor_stand_greyskull.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/armor_stand_skeleton.json
  data/foxcraft_dungeon_loot/loot_tables/items/common/armor_stand_zombie.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_burning_rage.json
  data/foxcraft_dungeon_loot/loot_tables/items/rare/aurelias_lucky_compass.json
  data/foxcraft_dungeon_loot/loot_tables/items/rare/lucky_rabbits_foot.json
  data/foxcraft_dungeon_loot/loot_tables/items/uncommon/totem_of_undying.json
  src/foxcraft_dungeon_loot/items.mc
Labels: enhancement

#42 🔊 Add custom sound entries for Hammer of Sol
  src/foxcraft_dungeon_loot/items/hammer_of_sol.mc
  texturepack/assets/foxcraft_dungeon_loot/sounds.json
  texturepack/assets/minecraft/lang/en_us.json
Labels: enhancement, ui / ux

#43 🐛 Hammer of Sol now searches via raycast
  data/foxcraft_dungeon_loot/tags/blocks/raycast_pass.json
  data/foxcraft_dungeon_loot/tags/entity_types/markers.json
  src/foxcraft_dungeon_loot/items/hammer_of_sol.mc
Labels: bug

#44 ⚡ NBT to Predicate Conversion - Satyrnidae/issue20
  config.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/quet_zalas_beloved.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/totem_of_ekila.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/totem_of_gnumoch.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d10.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d100.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d12.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d2.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d20.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d4.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d5.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d6.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d8.json
  data/foxcraft_dungeon_loot/loot_tables/util/dice/roll_d9.json
  data/foxcraft_dungeon_loot/predicates/is_flying.json
  data/foxcraft_dungeon_loot/predicates/is_on_ground.json
  data/foxcraft_dungeon_loot/predicates/is_persistent.json
  data/foxcraft_dungeon_loot/predicates/items/chestplate_broken.json
  data/foxcraft_dungeon_loot/predicates/items/elytra_broken.json
  data/foxcraft_dungeon_loot/predicates/items/gravilock_boots/is_diamond.json
  data/foxcraft_dungeon_loot/predicates/items/gravilock_boots/is_iron.json
  data/foxcraft_dungeon_loot/predicates/items/hammer_of_sol/should_expire.json
  data/foxcraft_dungeon_loot/predicates/items/helmet_broken.json
  data/foxcraft_dungeon_loot/predicates/items/is_dice.json
  data/foxcraft_dungeon_loot/predicates/items/leggings_broken.json
  data/foxcraft_dungeon_loot/predicates/items/mainhand_broken.json
  data/foxcraft_dungeon_loot/predicates/items/offhand_broken.json
  data/foxcraft_dungeon_loot/predicates/items/wing_of_ouet_zala/in_inventory.json
  data/foxcraft_dungeon_loot/predicates/items/wing_of_quet_zala/in_inventory.json
  src/foxcraft_dungeon_loot.mc
  src/foxcraft_dungeon_loot/items/downpour_amulet.mc
  src/foxcraft_dungeon_loot/items/evokers_tome.mc
  src/foxcraft_dungeon_loot/items/gravilock_boots.mc
  src/foxcraft_dungeon_loot/items/hammer_of_sol.mc
  src/foxcraft_dungeon_loot/items/how_about_no.mc
  src/foxcraft_dungeon_loot/items/poncho_sanchezs_fate.mc
  src/foxcraft_dungeon_loot/items/quet_zalas_beloved.mc
  src/foxcraft_dungeon_loot/items/scripture_of_cleansing.mc
  src/foxcraft_dungeon_loot/items/totem_of_ekila.mc
  src/foxcraft_dungeon_loot/items/totem_of_gnumoch.mc
  src/foxcraft_dungeon_loot/items/totem_of_mysteria.mc
  src/foxcraft_dungeon_loot/items/war_hogs_disdainful_pride.mc
  src/foxcraft_dungeon_loot/items/wing_of_ouet_zala.mc
  src/foxcraft_dungeon_loot/items/wing_of_quet_zala.mc
  src/macros.mcm
Labels: enhancement

#46 💄 Improve textures for Hammer of Sol and Ima Leaf
  data/foxcraft_dungeon_loot/loot_tables/items/rare/ima_leaf.json
  data/foxcraft_dungeon_loot/tags/functions/on_tick.json
  src/foxcraft_dungeon_loot/items/ima_leaf.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/ima_leaf.json
  texturepack/assets/foxcraft_dungeon_loot/textures/item/hammer_of_sol.png
  texturepack/assets/foxcraft_dungeon_loot/textures/item/ima_leaf.png
  texturepack/assets/foxcraft_dungeon_loot/textures/item/ima_leave.png
  texturepack/assets/minecraft/models/item/warped_fungus_on_a_stick.json
Labels: ui / ux

#50 ✨ Add Hail of Arrows Spell Scroll
  data/foxcraft_dungeon_loot/loot_tables/items/epic/spell_scroll_hail_of_arrows.json
  data/foxcraft_dungeon_loot/tags/functions/on_tick.json
  src/foxcraft_dungeon_loot/items/spell_scroll_hail_of_arrows.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/spell_scroll_hail_of_arrows.json
  texturepack/assets/foxcraft_dungeon_loot/textures/item/spell_scroll.png
  texturepack/assets/minecraft/models/item/snowball.json
Labels: enhancement

#52 ✨ Add X No Evil
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/x_no_evil.json
  data/foxcraft_dungeon_loot/predicates/items/x_no_evil/is_new_aoe_cloud.json
  data/foxcraft_dungeon_loot/tags/functions/on_tick.json
  src/foxcraft_dungeon_loot.mc
  src/foxcraft_dungeon_loot/items/x_no_evil.mc
  src/foxcraft_dungeon_loot/math.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/air.json
  texturepack/assets/minecraft/models/item/snowball.json
  texturepack/assets/minecraft/models/item/warped_fungus_on_a_stick.json
Labels: enhancement

#56 ✨ Implement Tor'Enhia's Fist
  data/foxcraft_dungeon_loot/loot_tables/items/epic/torenhias_fist.json
  data/foxcraft_dungeon_loot/predicates/items/is_mainhand_snowball.json
  data/foxcraft_dungeon_loot/tags/functions/on_load.json
  data/foxcraft_dungeon_loot/tags/functions/on_tick.json
  src/foxcraft_dungeon_loot.mc
  src/foxcraft_dungeon_loot/items/torenhias_fist.mc
  src/foxcraft_dungeon_loot/items/x_no_evil.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/torenhias_fist.json
  texturepack/assets/foxcraft_dungeon_loot/sounds.json
  texturepack/assets/foxcraft_dungeon_loot/textures/item/torenhias_fist.png
  texturepack/assets/minecraft/lang/en_us.json
  texturepack/assets/minecraft/models/item/snowball.json
Labels: enhancement

#57 🐛 Snowball items need to work in either hand
  src/foxcraft_dungeon_loot/items/hammer_of_sol.mc
  src/foxcraft_dungeon_loot/items/spell_scroll_hail_of_arrows.mc
  src/foxcraft_dungeon_loot/items/torenhias_fist.mc
  src/foxcraft_dungeon_loot/items/x_no_evil.mc
Labels: bug

#59 🐛 Prevent use of item when offhand would be used
  data/foxcraft_dungeon_loot/predicates/items/offhand_prevents_use.json
  data/foxcraft_dungeon_loot/tags/items/prevents_use.json
  src/foxcraft_dungeon_loot/items/bringer_of_fear.mc
  src/foxcraft_dungeon_loot/items/d10.mc
  src/foxcraft_dungeon_loot/items/d12.mc
  src/foxcraft_dungeon_loot/items/d20.mc
  src/foxcraft_dungeon_loot/items/d4.mc
  src/foxcraft_dungeon_loot/items/d6.mc
  src/foxcraft_dungeon_loot/items/d8.mc
  src/foxcraft_dungeon_loot/items/deilonas_holy_blessings.mc
  src/foxcraft_dungeon_loot/items/downpour_amulet.mc
  src/foxcraft_dungeon_loot/items/evokers_tome.mc
  src/foxcraft_dungeon_loot/items/eye_cream.mc
  src/foxcraft_dungeon_loot/items/feather_of_quet_zala.mc
  src/foxcraft_dungeon_loot/items/gift_of_sheep_island.mc
  src/foxcraft_dungeon_loot/items/heros_amulet.mc
  src/foxcraft_dungeon_loot/items/how_about_no.mc
  src/foxcraft_dungeon_loot/items/ima_leaf.mc
  src/foxcraft_dungeon_loot/items/poncho_sanchezs_fate.mc
  src/foxcraft_dungeon_loot/items/pride_and_extreme_prejudice.mc
  src/foxcraft_dungeon_loot/items/scripture_of_cleansing.mc
  src/foxcraft_dungeon_loot/items/silverfish_escape_artist.mc
Labels: bug

#60 ♻️ Remove unnecessary if entity checks
  src/foxcraft_dungeon_loot/items/evokers_tome.mc
  src/foxcraft_dungeon_loot/items/hammer_of_sol.mc
  src/foxcraft_dungeon_loot/items/love_wheat.mc
  src/foxcraft_dungeon_loot/items/spell_scroll_hail_of_arrows.mc
Labels: enhancement

#63 🐛 Ensure items no longer overrun their cooldowns
  src/foxcraft_dungeon_loot/items/pride_and_extreme_prejudice.mc
  src/foxcraft_dungeon_loot/items/scripture_of_cleansing.mc
Labels: bug, investigation

#75 ✨ Add Tithe to Uthiir sword
  data/foxcraft_dungeon_loot/advancements/items/tithe_to_uthiir/on_hit.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/tithe_to_uthiir.json
  data/foxcraft_dungeon_loot/loot_tables/loot/epic.json
  data/foxcraft_dungeon_loot/predicates/events/process_spider_eye.json
  data/foxcraft_dungeon_loot/tags/entity_types/arthropods.json
  data/foxcraft_dungeon_loot/tags/functions/on_spider_eye_eaten.json
  src/foxcraft_dungeon_loot/events.mc
  src/foxcraft_dungeon_loot/items/estudinaes_sorrow.mc
  src/foxcraft_dungeon_loot/items/tithe_to_uthiir.mc
  src/foxcraft_dungeon_loot/trades/index.mc
  src/foxcraft_dungeon_loot/trades/wandering_trader.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/tithe_to_uthiir.json
  texturepack/assets/foxcraft_dungeon_loot/textures/item/tithe_to_uthiir.png
  texturepack/assets/foxcraft_dungeon_loot/textures/item/tithe_to_uthiir_layer1.png
  texturepack/assets/foxcraft_dungeon_loot/textures/item/tithe_to_uthiir_layer2.png
  texturepack/assets/minecraft/models/item/netherite_sword.json
  texturepack/pack.mcmeta
Labels: enhancement

#76 ✨ Add sword-shield-thing
  README.md
  data/foxcraft_dungeon_loot/advancements/items/beta_iron_sword/on_hit.json
  data/foxcraft_dungeon_loot/item_modifiers/beta_iron_sword/on_hit.json
  data/foxcraft_dungeon_loot/loot_tables/items/rare/beta_iron_sword.json
  data/foxcraft_dungeon_loot/loot_tables/loot/rare.json
  data/foxcraft_dungeon_loot/predicates/events/process_block.json
  data/foxcraft_dungeon_loot/tags/functions/on_block.json
  data/foxcraft_dungeon_loot/tags/functions/on_load.json
  data/foxcraft_dungeon_loot/tags/functions/on_tick.json
  data/foxcraft_dungeon_loot/tags/functions/on_uninstall.json
  src/foxcraft_dungeon_loot.mc
  src/foxcraft_dungeon_loot/events.mc
  src/foxcraft_dungeon_loot/items/beta_iron_sword.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/iron_sword_blocking.json
  texturepack/assets/foxcraft_dungeon_loot/sounds.json
  texturepack/assets/foxcraft_dungeon_loot/sounds/items/beta_iron_sword/block1.ogg
  texturepack/assets/foxcraft_dungeon_loot/sounds/items/beta_iron_sword/block2.ogg
  texturepack/assets/minecraft/models/item/shield.json
Labels: enhancement

#77 🐛 Wandering traders are losing their llamas.
  data/foxcraft_dungeon_loot/loot_tables/loot/advancements/dungeon_item_trade.json
  data/foxcraft_dungeon_loot/loot_tables/loot/coins/copper_coins.json
  data/foxcraft_dungeon_loot/loot_tables/loot/coins/electrum_coins.json
  data/foxcraft_dungeon_loot/loot_tables/loot/coins/gold_coins.json
  data/foxcraft_dungeon_loot/loot_tables/loot/coins/platinum_coins.json
  data/foxcraft_dungeon_loot/loot_tables/loot/coins/silver_coins.json
  data/minecraft/loot_tables/entities/wandering_trader.json
  src/foxcraft_dungeon_loot/trades.mc
  src/foxcraft_dungeon_loot/trades/index.mc
  src/foxcraft_dungeon_loot/trades/wandering_trader.mc
Labels: bug

#79 ✨ Add fake AOE cloud to Deilona's Holy Blessings
  src/foxcraft_dungeon_loot/items/deilonas_holy_blessings.mc
Labels: enhancement

#80 ⚡ Increase performance of on_fall check
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/quet_zalas_beloved.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_disdainful_pride.json
  data/foxcraft_dungeon_loot/predicates/events/process_fall.json
  src/foxcraft_dungeon_loot/events.mc
Labels: performance

#81 🐛 Buff Dawncleaver fire aspect to V
  data/foxcraft_dungeon_loot/loot_tables/items/epic/dawncleaver.json
Labels: bug

#82 🐛 Nerf passive resistance value on items
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/talking_stick.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/totem_of_dendris.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/totem_of_gnumoch.json
  data/foxcraft_dungeon_loot/predicates/items/talking_stick/has_effects.json
  data/foxcraft_dungeon_loot/predicates/items/totem_of_dendris/has_effects.json
  data/foxcraft_dungeon_loot/predicates/items/totem_of_gnumoch/has_effects.json
  src/foxcraft_dungeon_loot/items/talking_stick.mc
  src/foxcraft_dungeon_loot/items/totem_of_dendris.mc
  src/foxcraft_dungeon_loot/items/totem_of_gnumoch.mc
Labels: bug

#83 ✨ Add Grasp of Uthiir snowball item
  data/foxcraft_dungeon_loot/loot_tables/items/rare/grasp_of_uthiir.json
  data/foxcraft_dungeon_loot/loot_tables/loot/rare.json
  data/foxcraft_dungeon_loot/predicates/items/grasp_of_uthiir/in_main_hand.json
  data/foxcraft_dungeon_loot/predicates/items/grasp_of_uthiir/in_off_hand.json
  data/foxcraft_dungeon_loot/tags/functions/on_snowball_used.json
  data/foxcraft_dungeon_loot/tags/functions/on_tick.json
  src/foxcraft_dungeon_loot/items/grasp_of_uthiir.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/grasp_of_uthiir.json
  texturepack/assets/minecraft/models/item/snowball.json
Labels: enhancement

#86 🐛 Add missing scoreboards
  data/foxcraft_dungeon_loot/loot_tables/loot/uncommon.json
  data/foxcraft_dungeon_loot/tags/functions/on_load.json
  data/foxcraft_dungeon_loot/tags/functions/on_uninstall.json
  src/foxcraft_dungeon_loot/items/bringer_of_fear.mc
  src/foxcraft_dungeon_loot/items/evokers_tome.mc
  src/foxcraft_dungeon_loot/items/torenhias_fist.mc
Labels: bug

#87 ⚡ Math refactor
  config.json
  data/foxcraft_dungeon_loot/predicates/items/chest_has_unbreaking.json
  data/foxcraft_dungeon_loot/predicates/items/feet_have_unbreaking.json
  data/foxcraft_dungeon_loot/predicates/items/mainhand_has_unbreaking.json
  data/foxcraft_dungeon_loot/tags/functions/on_uninstall.json
  src/foxcraft_dungeon_loot.mc
  src/foxcraft_dungeon_loot/items/beta_iron_sword.mc
  src/foxcraft_dungeon_loot/items/bringer_of_fear.mc
  src/foxcraft_dungeon_loot/items/d10.mc
  src/foxcraft_dungeon_loot/items/d12.mc
  src/foxcraft_dungeon_loot/items/d20.mc
  src/foxcraft_dungeon_loot/items/d4.mc
  src/foxcraft_dungeon_loot/items/d6.mc
  src/foxcraft_dungeon_loot/items/d8.mc
  src/foxcraft_dungeon_loot/items/downpour_amulet.mc
  src/foxcraft_dungeon_loot/items/evokers_tome.mc
  src/foxcraft_dungeon_loot/items/eye_cream.mc
  src/foxcraft_dungeon_loot/items/gravilock_boots.mc
  src/foxcraft_dungeon_loot/items/heros_amulet.mc
  src/foxcraft_dungeon_loot/items/poncho_sanchezs_fate.mc
  src/foxcraft_dungeon_loot/items/pride_and_extreme_prejudice.mc
  src/foxcraft_dungeon_loot/items/quet_zalas_beloved.mc
  src/foxcraft_dungeon_loot/items/scripture_of_cleansing.mc
  src/foxcraft_dungeon_loot/items/tithe_to_uthiir.mc
  src/foxcraft_dungeon_loot/items/torenhias_fist.mc
  src/foxcraft_dungeon_loot/items/war_hogs_burning_rage.mc
  src/foxcraft_dungeon_loot/items/war_hogs_disdainful_pride.mc
  src/foxcraft_dungeon_loot/items/x_no_evil.mc
  src/foxcraft_dungeon_loot/math.mc
  src/foxcraft_dungeon_loot/trades.mcm
  src/foxcraft_dungeon_loot/trades/wandering_trader.mc
  src/macros.mcm
Labels: enhancement

#88 ✨ Add unobtainable potions to the loot tables
  data/foxcraft_dungeon_loot/loot_tables/items/epic/estudinaes_sorrow.json
  data/foxcraft_dungeon_loot/loot_tables/loot/books/palomina_and_the_demon_lord.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_fortune.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_fortune_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_fortune_3.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_fortune_4.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_fortune_5.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_grace.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_haste.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_haste_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_heroism.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_satiation.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_satiation_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_satiation_3.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_satiation_4.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_satiation_5.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_vitality.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_vitality_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_warding.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/potion_of_warding_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_blindness.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_calamity.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_calamity_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_calamity_3.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_calamity_4.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_calamity_5.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_darkness.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_decay.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_decay_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_decay_3.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_famine.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_famine_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_famine_3.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_fatigue.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_fatigue_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_fatigue_3.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_levitation.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_levitation_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_levitation_3.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_luminance.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_misfortune.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_misfortune_2.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_misfortune_3.json
  data/foxcraft_dungeon_loot/loot_tables/loot/potions/splash_potion_of_nausea.json
  src/foxcraft_dungeon_loot/items/estudinaes_sorrow.mc
Labels: enhancement

#89 ✨ Nerf Buckwheat
  data/foxcraft_dungeon_loot/item_modifiers/buckwheat/damage_1.json
  data/foxcraft_dungeon_loot/item_modifiers/buckwheat/damage_10.json
  data/foxcraft_dungeon_loot/item_modifiers/buckwheat/damage_2.json
  data/foxcraft_dungeon_loot/item_modifiers/buckwheat/damage_4.json
  data/foxcraft_dungeon_loot/item_modifiers/buckwheat/damage_6.json
  data/foxcraft_dungeon_loot/item_modifiers/buckwheat/damage_8.json
  data/foxcraft_dungeon_loot/loot_tables/items/epic/buckwheat.json
  data/foxcraft_dungeon_loot/predicates/items/buckwheat/can_breed.json
  src/foxcraft_dungeon_loot/items/buckwheat.mc
  texturepack/assets/foxcraft_dungeon_loot/models/item/buckwheat.json
  texturepack/assets/minecraft/models/item/warped_fungus_on_a_stick.json
  texturepack/pack.mcmeta
Labels: enhancement

#94 🐛 Reduce downpour amulet cooldown step
  src/foxcraft_dungeon_loot/items/downpour_amulet.mc
Labels: bug

#96 🐛 Fix typo when checking bringer of fear cooldown
  src/foxcraft_dungeon_loot/items/bringer_of_fear.mc
Labels: bug

#103 ✨ Add wither effect to Estudinae's Sorrow
  data/foxcraft_dungeon_loot/loot_tables/items/epic/estudinaes_sorrow.json
  src/foxcraft_dungeon_loot/items/estudinaes_sorrow.mc
Labels: enhancement

#101 ✨ Convert War Hog's Rage to raycast solution
  data/foxcraft_dungeon_loot/advancements/items/tithe_to_uthiir/on_hit.json
  data/foxcraft_dungeon_loot/advancements/items/war_hogs_burning_rage/on_hit.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_burning_rage.json
  src/foxcraft_dungeon_loot/items/war_hogs_burning_rage.mc
Labels: enhancement

#100 💄 Brighten all coin textures
  texturepack/assets/foxcraft_dungeon_loot/textures/item/copper_coins.png
  texturepack/assets/foxcraft_dungeon_loot/textures/item/electrum_coins.png
  texturepack/assets/foxcraft_dungeon_loot/textures/item/gold_coins.png
  texturepack/assets/foxcraft_dungeon_loot/textures/item/platinum_coins.png
  texturepack/assets/foxcraft_dungeon_loot/textures/item/silver_coins.png
  texturepack/pack.mcmeta
Labels: enhancement, ui / ux

#99 ✨ Nerf Downpour Amulet thunder activation
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/downpour_amulet.json
  src/foxcraft_dungeon_loot/items/downpour_amulet.mc
Labels: bug, enhancement

#97 ✨ Reduce slow fall activation to 500cm
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/quet_zalas_beloved.json
  data/foxcraft_dungeon_loot/loot_tables/items/mythic/war_hogs_disdainful_pride.json
  src/foxcraft_dungeon_loot/events.mc
Labels: enhancement

#108 ✨ Trader overhaul
  src/foxcraft_dungeon_loot/trades.mc
  src/foxcraft_dungeon_loot/trades/wandering_trader.mc
Labels: enhancement

#110 ✨ Add more items to the common grab bags
  data/foxcraft_dungeon_loot/loot_tables/loot/common.json
  data/foxcraft_dungeon_loot/loot_tables/loot/grab_bag/common.json
  data/foxcraft_dungeon_loot/loot_tables/loot/grab_bag/epic.json
  data/foxcraft_dungeon_loot/loot_tables/loot/grab_bag/mythic.json
  data/foxcraft_dungeon_loot/loot_tables/loot/grab_bag/rare.json
  data/foxcraft_dungeon_loot/loot_tables/loot/grab_bag/uncommon.json
  data/foxcraft_dungeon_loot/loot_tables/single_armor_stand.json
  data/foxcraft_dungeon_loot/loot_tables/single_axe.json
  data/foxcraft_dungeon_loot/loot_tables/single_copper_goat_horn.json
  data/foxcraft_dungeon_loot/loot_tables/single_die.json
  data/foxcraft_dungeon_loot/loot_tables/single_drink.json
  data/foxcraft_dungeon_loot/loot_tables/single_hoe.json
  data/foxcraft_dungeon_loot/loot_tables/single_pickaxe.json
  data/foxcraft_dungeon_loot/loot_tables/single_resource.json
  data/foxcraft_dungeon_loot/loot_tables/single_shovel.json
  data/foxcraft_dungeon_loot/loot_tables/single_spawn_egg.json
  data/foxcraft_dungeon_loot/loot_tables/single_sword.json
  data/foxcraft_dungeon_loot/loot_tables/single_tool.json
  data/foxcraft_dungeon_loot/loot_tables/single_weapon.json
Labels: enhancement

#112 ✨ Add a spam lockout for dice.
  data/foxcraft_dungeon_loot/tags/functions/on_load.json
  data/foxcraft_dungeon_loot/tags/functions/on_tick.json
  data/foxcraft_dungeon_loot/tags/functions/on_uninstall.json
  data/foxcraft_dungeon_loot/tags/functions/on_warped_fungus_used.json
  src/foxcraft_dungeon_loot.mc
  src/foxcraft_dungeon_loot/items/copper_goat_horn.mc
  src/foxcraft_dungeon_loot/items/d10.mc
  src/foxcraft_dungeon_loot/items/d12.mc
  src/foxcraft_dungeon_loot/items/d20.mc
  src/foxcraft_dungeon_loot/items/d4.mc
  src/foxcraft_dungeon_loot/items/d6.mc
  src/foxcraft_dungeon_loot/items/d8.mc
  src/foxcraft_dungeon_loot/items/dice.mc
  src/foxcraft_dungeon_loot/trades.mc
Labels: enhancement

#114 ✨ Make certain counters configurable
  data/foxcraft_dungeon_loot/advancements/items/war_hogs_burning_rage/on_hit.json
  src/foxcraft_dungeon_loot/items/bringer_of_fear.mc
  src/foxcraft_dungeon_loot/items/deilonas_holy_blessings.mc
  src/foxcraft_dungeon_loot/items/downpour_amulet.mc
  src/foxcraft_dungeon_loot/items/feather_of_quet_zala.mc
  src/foxcraft_dungeon_loot/items/how_about_no.mc
  src/foxcraft_dungeon_loot/items/poncho_sanchezs_fate.mc
  src/foxcraft_dungeon_loot/items/pride_and_extreme_prejudice.mc
  src/foxcraft_dungeon_loot/items/scripture_of_cleansing.mc
  src/foxcraft_dungeon_loot/items/silverfish_escape_artist.mc
  src/foxcraft_dungeon_loot/items/war_hogs_burning_rage.mc
  src/foxcraft_dungeon_loot/math.mc
Labels: enhancement
